################################################################################
# Gitlab CI for Drupal 7 project, code quality and deploy.
#
# Project: https://repository.unesco.org/gitlab/drupal/unescorg
# Documentation: https://repository.unesco.org/gitlab/drupal/unescorg
# Inspired by: https://gitlab.com/mog33/gitlab-ci-drupal
#              https://blog.callr.tech/gitlab-ansible-docker-ci-cd/
#
# License: GPL-3
#
################################################################################

variables:

################################################################################
# Define your stages, this will be "pipelines" in gitlab.
#   https://docs.gitlab.com/ee/ci/pipelines.html
################################################################################
stages:
  - build
  - deploy

################################################################################
# Build Template
################################################################################
build:
  stage: build
  tags:
    - docker
  when: always
  artifacts:
    untracked: true
    expire_in: 1 hour
    when: on_success
    paths:
      - style-guide
      - assets
  allow_failure: false
  before_script: 
    - git fetch --all
    - git checkout $CI_COMMIT_REF_NAME
    - git reset --hard origin/$CI_COMMIT_REF_NAME
  script:
    - npm ci
    - gulp build

################################################################################
# Deploy stage:
# Depends on test in stage
# TODO: check for unwanted modules
################################################################################
deploy_stage:
  stage: deploy
  tags:
    - deploy
    - shell
  only:
    - develop
  except:
    - master
  allow_failure: false
  before_script:
    - which ssh-agent || ( apt update -y && apt install openssh-client -y )
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H repository.unesco.org >> ~/.ssh/known_hosts
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://en.srvbltydev.unesco.org/typography
  dependencies:
    - build
  when: on_success
  script:
    - rsync -acerOo --delete -e "ssh -p22 -oStrictHostKeyChecking=no" style-guide/* assets javascripts favicon.ico denix@$STAGE_HOST:$GIT_ROOT/typography

################################################################################
# Deploy prod:
# Secure everything, disable views
################################################################################
deploy_production:
  stage: deploy
  tags:
    - deploy
    - shell
  only:
    - master
  when: manual
  dependencies:
    - build
  before_script:
    - which ssh-agent || ( apt update -y && apt install openssh-client -y )
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - rsync -acerOo --delete -e "ssh -p22 -oStrictHostKeyChecking=no -i ~/.ssh/id_rsa_deploy" style-guide/* favicon.ico assets javascripts denix@$PRODUCTION_HOST:$GIT_ROOT_PROD/typography
  environment:
    name: prod
    url: https://en.unesco.org/typography
